---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocs-osd-deployer
  namespace: openshift-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocs-osd-deployer
  namespace: openshift-storage
rules:
  - apiGroups: ["ocs.openshift.io"]
    resources: ["storageclusters"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocs-osd-deployer
  namespace: openshift-storage
subjects:
  - kind: ServiceAccount
    name: ocs-osd-deployer
roleRef:
  kind: Role
  name: ocs-osd-deployer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-osd-deployer
  namespace: openshift-storage
spec:
  selector:
    matchLabels:
      app: ocs-osd-deployer
  replicas: 1
  strategy:
    # On update, kill all the old then create the new
    type: Recreate
  template:
    metadata:
      labels:
        app: ocs-osd-deployer
    spec:
      containers:
        - env:
            - name: QUOTA_COUNT
              value: "1"
          name: deployer
          image: quay.io/johnstrunk/ocs-osd-deployer:latest
          imagePullPolicy: Always
      serviceAccountName: ocs-osd-deployer
