# permissions for end users to view managedocs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedocs-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - managedocs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - managedocs/status
  verbs:
  - get
